scroll button added
sourabhsikarwar/Scene-Movie-Platform pull request #134
Opened 2023-05-25 07:50 UTC by huzaifa9999

I have added the scroll to top button again , please check for further merge conflicts 
Thankyou

2023-05-25 14:44 UTC, sourabhsikarwar approved these changes

2023-05-25 14:45 UTC, sourabhsikarwar commented
Is there any specific need for yarn.lock files where npm is already in use? @huzaifa9999

2023-05-25 17:46 UTC, huzaifa9999 commented
> Is there any specific need for yarn.lock files where npm is already in use? @huzaifa9999

no there isn't , I haven't installed yarn.lock , it just automatically comes when I do npm i

2023-06-01 03:29 UTC, anjula-sack requested changes
There are some formatting issues. @sourabhsikarwar We better setup linters and code formatters.

2023-06-01 03:29 UTC, anjula-sack commented on src/components/ScrollBtn/ScrollToTop.jsx
> +
```suggestion
```

2023-06-01 03:29 UTC, anjula-sack commented on src/components/ScrollBtn/ScrollToTop.jsx
> +            {" "}
```suggestion
```

2023-06-01 03:29 UTC, anjula-sack commented on src/components/ScrollBtn/ScrollToTop.jsx
> +            )}{" "}
```suggestion
            )}
```

2023-06-01 03:29 UTC, anjula-sack commented on src/components/ScrollBtn/ScrollToTop.jsx
> +
```suggestion
```

2023-06-19 09:43 UTC, closed without merging