#139-fixing signUp button
sourabhsikarwar/Scene-Movie-Platform pull request #143
Opened 2023-05-27 08:02 UTC by Soulpurr

## Related Issue
SignUp button taking too much padding on mobile screens

Closes: #[issue number]
#139 

## Description of Changes
Decrease the padding of button

For example:
- Added a new function to handle XYZ.
- Updated the ABC module to fix the bug.
- Refactored code in the DEF class for improved performance.
-->

## Checklist:

- [x ] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.

## Screenshots
[scrnli_27_05_2023_13-32-26.webm](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/92094765/05ee983f-4a23-4696-9ae7-b809cb423703)

2023-05-29 01:54 UTC, Soulpurr commented
@sourabhsikarwar pls verify and approve this pr

2023-06-01 03:26 UTC, anjula-sack requested changes

2023-06-01 03:26 UTC, anjula-sack commented on src/style.js
> +  button2: "bg-blue-gradient border-0 text-black px-2 py-2  rounded shadow",
```suggestion
  button2: "bg-blue-gradient border-0 text-black px-2 py-2 rounded shadow",
```

2023-06-01 03:26 UTC, anjula-sack commented on src/style.js
> +  button2: "bg-blue-gradient border-0 text-black px-2 py-2  rounded shadow",
Let's remove this extra space

2023-06-01 11:22 UTC, Soulpurr commented on src/style.js
> +  button2: "bg-blue-gradient border-0 text-black px-2 py-2  rounded shadow",
@anjula-sack reomoved the extra space

2023-11-26 06:05 UTC, closed without merging